/*
 * Tapdata OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: moa-v1.1.0-117-g6b02a67
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tapdata.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;

/**
 * Customer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-07-29T11:08:48.431+08:00[Asia/Shanghai]")
public class Customer {
  public static final String SERIALIZED_NAME_ID = "_id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_C_U_S_T_O_M_E_R_I_D = "CUSTOMER_ID";
  @SerializedName(SERIALIZED_NAME_C_U_S_T_O_M_E_R_I_D)
  private String CUSTOMER_ID;

  public static final String SERIALIZED_NAME_C_I_T_Y = "CITY";
  @SerializedName(SERIALIZED_NAME_C_I_T_Y)
  private String CITY;

  public static final String SERIALIZED_NAME_C_O_U_N_T_R_Y_C_O_D_E = "COUNTRY_CODE";
  @SerializedName(SERIALIZED_NAME_C_O_U_N_T_R_Y_C_O_D_E)
  private String COUNTRY_CODE;

  public static final String SERIALIZED_NAME_D_A_T_E_O_F_B_I_R_T_H = "DATE_OF_BIRTH";
  @SerializedName(SERIALIZED_NAME_D_A_T_E_O_F_B_I_R_T_H)
  private OffsetDateTime DATE_OF_BIRTH;

  public static final String SERIALIZED_NAME_E_M_A_I_L = "EMAIL";
  @SerializedName(SERIALIZED_NAME_E_M_A_I_L)
  private String EMAIL;

  public static final String SERIALIZED_NAME_F_I_R_S_T_N_A_M_E = "FIRST_NAME";
  @SerializedName(SERIALIZED_NAME_F_I_R_S_T_N_A_M_E)
  private String FIRST_NAME;

  public static final String SERIALIZED_NAME_G_E_N_D_E_R = "GENDER";
  @SerializedName(SERIALIZED_NAME_G_E_N_D_E_R)
  private String GENDER;

  public static final String SERIALIZED_NAME_J_O_B = "JOB";
  @SerializedName(SERIALIZED_NAME_J_O_B)
  private String JOB;

  public static final String SERIALIZED_NAME_L_A_S_T_C_H_A_N_G_E = "LAST_CHANGE";
  @SerializedName(SERIALIZED_NAME_L_A_S_T_C_H_A_N_G_E)
  private OffsetDateTime LAST_CHANGE;

  public static final String SERIALIZED_NAME_L_A_S_T_N_A_M_E = "LAST_NAME";
  @SerializedName(SERIALIZED_NAME_L_A_S_T_N_A_M_E)
  private String LAST_NAME;

  public static final String SERIALIZED_NAME_M_A_R_I_T_A_L_S_T_A_T_U_S = "MARITAL_STATUS";
  @SerializedName(SERIALIZED_NAME_M_A_R_I_T_A_L_S_T_A_T_U_S)
  private String MARITAL_STATUS;

  public static final String SERIALIZED_NAME_N_A_T_I_O_N_A_L_I_T_Y = "NATIONALITY";
  @SerializedName(SERIALIZED_NAME_N_A_T_I_O_N_A_L_I_T_Y)
  private String NATIONALITY;

  public static final String SERIALIZED_NAME_N_U_M_B_E_R_C_H_I_L_D_R_E_N = "NUMBER_CHILDREN";
  @SerializedName(SERIALIZED_NAME_N_U_M_B_E_R_C_H_I_L_D_R_E_N)
  private BigDecimal NUMBER_CHILDREN;

  public static final String SERIALIZED_NAME_P_H_O_N_E = "PHONE";
  @SerializedName(SERIALIZED_NAME_P_H_O_N_E)
  private String PHONE;

  public static final String SERIALIZED_NAME_S_T_R_E_E_T = "STREET";
  @SerializedName(SERIALIZED_NAME_S_T_R_E_E_T)
  private String STREET;

  public static final String SERIALIZED_NAME_Z_I_P = "ZIP";
  @SerializedName(SERIALIZED_NAME_Z_I_P)
  private String ZIP;

  public Customer id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Customer CUSTOMER_ID(String CUSTOMER_ID) {
    this.CUSTOMER_ID = CUSTOMER_ID;
    return this;
  }

   /**
   * Get CUSTOMER_ID
   * @return CUSTOMER_ID
  **/
  @ApiModelProperty(value = "")
  public String getCUSTOMERID() {
    return CUSTOMER_ID;
  }

  public void setCUSTOMERID(String CUSTOMER_ID) {
    this.CUSTOMER_ID = CUSTOMER_ID;
  }

  public Customer CITY(String CITY) {
    this.CITY = CITY;
    return this;
  }

   /**
   * Get CITY
   * @return CITY
  **/
  @ApiModelProperty(value = "")
  public String getCITY() {
    return CITY;
  }

  public void setCITY(String CITY) {
    this.CITY = CITY;
  }

  public Customer COUNTRY_CODE(String COUNTRY_CODE) {
    this.COUNTRY_CODE = COUNTRY_CODE;
    return this;
  }

   /**
   * Get COUNTRY_CODE
   * @return COUNTRY_CODE
  **/
  @ApiModelProperty(value = "")
  public String getCOUNTRYCODE() {
    return COUNTRY_CODE;
  }

  public void setCOUNTRYCODE(String COUNTRY_CODE) {
    this.COUNTRY_CODE = COUNTRY_CODE;
  }

  public Customer DATE_OF_BIRTH(OffsetDateTime DATE_OF_BIRTH) {
    this.DATE_OF_BIRTH = DATE_OF_BIRTH;
    return this;
  }

   /**
   * Get DATE_OF_BIRTH
   * @return DATE_OF_BIRTH
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDATEOFBIRTH() {
    return DATE_OF_BIRTH;
  }

  public void setDATEOFBIRTH(OffsetDateTime DATE_OF_BIRTH) {
    this.DATE_OF_BIRTH = DATE_OF_BIRTH;
  }

  public Customer EMAIL(String EMAIL) {
    this.EMAIL = EMAIL;
    return this;
  }

   /**
   * Get EMAIL
   * @return EMAIL
  **/
  @ApiModelProperty(value = "")
  public String getEMAIL() {
    return EMAIL;
  }

  public void setEMAIL(String EMAIL) {
    this.EMAIL = EMAIL;
  }

  public Customer FIRST_NAME(String FIRST_NAME) {
    this.FIRST_NAME = FIRST_NAME;
    return this;
  }

   /**
   * Get FIRST_NAME
   * @return FIRST_NAME
  **/
  @ApiModelProperty(value = "")
  public String getFIRSTNAME() {
    return FIRST_NAME;
  }

  public void setFIRSTNAME(String FIRST_NAME) {
    this.FIRST_NAME = FIRST_NAME;
  }

  public Customer GENDER(String GENDER) {
    this.GENDER = GENDER;
    return this;
  }

   /**
   * Get GENDER
   * @return GENDER
  **/
  @ApiModelProperty(value = "")
  public String getGENDER() {
    return GENDER;
  }

  public void setGENDER(String GENDER) {
    this.GENDER = GENDER;
  }

  public Customer JOB(String JOB) {
    this.JOB = JOB;
    return this;
  }

   /**
   * Get JOB
   * @return JOB
  **/
  @ApiModelProperty(value = "")
  public String getJOB() {
    return JOB;
  }

  public void setJOB(String JOB) {
    this.JOB = JOB;
  }

  public Customer LAST_CHANGE(OffsetDateTime LAST_CHANGE) {
    this.LAST_CHANGE = LAST_CHANGE;
    return this;
  }

   /**
   * Get LAST_CHANGE
   * @return LAST_CHANGE
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLASTCHANGE() {
    return LAST_CHANGE;
  }

  public void setLASTCHANGE(OffsetDateTime LAST_CHANGE) {
    this.LAST_CHANGE = LAST_CHANGE;
  }

  public Customer LAST_NAME(String LAST_NAME) {
    this.LAST_NAME = LAST_NAME;
    return this;
  }

   /**
   * Get LAST_NAME
   * @return LAST_NAME
  **/
  @ApiModelProperty(value = "")
  public String getLASTNAME() {
    return LAST_NAME;
  }

  public void setLASTNAME(String LAST_NAME) {
    this.LAST_NAME = LAST_NAME;
  }

  public Customer MARITAL_STATUS(String MARITAL_STATUS) {
    this.MARITAL_STATUS = MARITAL_STATUS;
    return this;
  }

   /**
   * Get MARITAL_STATUS
   * @return MARITAL_STATUS
  **/
  @ApiModelProperty(value = "")
  public String getMARITALSTATUS() {
    return MARITAL_STATUS;
  }

  public void setMARITALSTATUS(String MARITAL_STATUS) {
    this.MARITAL_STATUS = MARITAL_STATUS;
  }

  public Customer NATIONALITY(String NATIONALITY) {
    this.NATIONALITY = NATIONALITY;
    return this;
  }

   /**
   * Get NATIONALITY
   * @return NATIONALITY
  **/
  @ApiModelProperty(value = "")
  public String getNATIONALITY() {
    return NATIONALITY;
  }

  public void setNATIONALITY(String NATIONALITY) {
    this.NATIONALITY = NATIONALITY;
  }

  public Customer NUMBER_CHILDREN(BigDecimal NUMBER_CHILDREN) {
    this.NUMBER_CHILDREN = NUMBER_CHILDREN;
    return this;
  }

   /**
   * Get NUMBER_CHILDREN
   * @return NUMBER_CHILDREN
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getNUMBERCHILDREN() {
    return NUMBER_CHILDREN;
  }

  public void setNUMBERCHILDREN(BigDecimal NUMBER_CHILDREN) {
    this.NUMBER_CHILDREN = NUMBER_CHILDREN;
  }

  public Customer PHONE(String PHONE) {
    this.PHONE = PHONE;
    return this;
  }

   /**
   * Get PHONE
   * @return PHONE
  **/
  @ApiModelProperty(value = "")
  public String getPHONE() {
    return PHONE;
  }

  public void setPHONE(String PHONE) {
    this.PHONE = PHONE;
  }

  public Customer STREET(String STREET) {
    this.STREET = STREET;
    return this;
  }

   /**
   * Get STREET
   * @return STREET
  **/
  @ApiModelProperty(value = "")
  public String getSTREET() {
    return STREET;
  }

  public void setSTREET(String STREET) {
    this.STREET = STREET;
  }

  public Customer ZIP(String ZIP) {
    this.ZIP = ZIP;
    return this;
  }

   /**
   * Get ZIP
   * @return ZIP
  **/
  @ApiModelProperty(value = "")
  public String getZIP() {
    return ZIP;
  }

  public void setZIP(String ZIP) {
    this.ZIP = ZIP;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.id, customer.id) &&
        Objects.equals(this.CUSTOMER_ID, customer.CUSTOMER_ID) &&
        Objects.equals(this.CITY, customer.CITY) &&
        Objects.equals(this.COUNTRY_CODE, customer.COUNTRY_CODE) &&
        Objects.equals(this.DATE_OF_BIRTH, customer.DATE_OF_BIRTH) &&
        Objects.equals(this.EMAIL, customer.EMAIL) &&
        Objects.equals(this.FIRST_NAME, customer.FIRST_NAME) &&
        Objects.equals(this.GENDER, customer.GENDER) &&
        Objects.equals(this.JOB, customer.JOB) &&
        Objects.equals(this.LAST_CHANGE, customer.LAST_CHANGE) &&
        Objects.equals(this.LAST_NAME, customer.LAST_NAME) &&
        Objects.equals(this.MARITAL_STATUS, customer.MARITAL_STATUS) &&
        Objects.equals(this.NATIONALITY, customer.NATIONALITY) &&
        Objects.equals(this.NUMBER_CHILDREN, customer.NUMBER_CHILDREN) &&
        Objects.equals(this.PHONE, customer.PHONE) &&
        Objects.equals(this.STREET, customer.STREET) &&
        Objects.equals(this.ZIP, customer.ZIP);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, CUSTOMER_ID, CITY, COUNTRY_CODE, DATE_OF_BIRTH, EMAIL, FIRST_NAME, GENDER, JOB, LAST_CHANGE, LAST_NAME, MARITAL_STATUS, NATIONALITY, NUMBER_CHILDREN, PHONE, STREET, ZIP);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    CUSTOMER_ID: ").append(toIndentedString(CUSTOMER_ID)).append("\n");
    sb.append("    CITY: ").append(toIndentedString(CITY)).append("\n");
    sb.append("    COUNTRY_CODE: ").append(toIndentedString(COUNTRY_CODE)).append("\n");
    sb.append("    DATE_OF_BIRTH: ").append(toIndentedString(DATE_OF_BIRTH)).append("\n");
    sb.append("    EMAIL: ").append(toIndentedString(EMAIL)).append("\n");
    sb.append("    FIRST_NAME: ").append(toIndentedString(FIRST_NAME)).append("\n");
    sb.append("    GENDER: ").append(toIndentedString(GENDER)).append("\n");
    sb.append("    JOB: ").append(toIndentedString(JOB)).append("\n");
    sb.append("    LAST_CHANGE: ").append(toIndentedString(LAST_CHANGE)).append("\n");
    sb.append("    LAST_NAME: ").append(toIndentedString(LAST_NAME)).append("\n");
    sb.append("    MARITAL_STATUS: ").append(toIndentedString(MARITAL_STATUS)).append("\n");
    sb.append("    NATIONALITY: ").append(toIndentedString(NATIONALITY)).append("\n");
    sb.append("    NUMBER_CHILDREN: ").append(toIndentedString(NUMBER_CHILDREN)).append("\n");
    sb.append("    PHONE: ").append(toIndentedString(PHONE)).append("\n");
    sb.append("    STREET: ").append(toIndentedString(STREET)).append("\n");
    sb.append("    ZIP: ").append(toIndentedString(ZIP)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

