/*
 * Tapdata OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: moa-v1.1.0-117-g6b02a67
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tapdata.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiV1TransactionLogFields
 */
public class ApiV1TransactionLogFieldsTest {
    private final ApiV1TransactionLogFields model = new ApiV1TransactionLogFields();

    /**
     * Model tests for ApiV1TransactionLogFields
     */
    @Test
    public void testApiV1TransactionLogFields() {
        // TODO: test ApiV1TransactionLogFields
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'CUSTOMER_ID'
     */
    @Test
    public void CUSTOMER_IDTest() {
        // TODO: test CUSTOMER_ID
    }

    /**
     * Test the property 'BUY_TIME'
     */
    @Test
    public void BUY_TIMETest() {
        // TODO: test BUY_TIME
    }

    /**
     * Test the property 'AMOUNT'
     */
    @Test
    public void AMOUNTTest() {
        // TODO: test AMOUNT
    }

    /**
     * Test the property 'SHOP'
     */
    @Test
    public void SHOPTest() {
        // TODO: test SHOP
    }

}
