/*
 * Tapdata OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: moa-v1.1.0-117-g6b02a67
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tapdata.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Customer
 */
public class CustomerTest {
    private final Customer model = new Customer();

    /**
     * Model tests for Customer
     */
    @Test
    public void testCustomer() {
        // TODO: test Customer
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'CUSTOMER_ID'
     */
    @Test
    public void CUSTOMER_IDTest() {
        // TODO: test CUSTOMER_ID
    }

    /**
     * Test the property 'CITY'
     */
    @Test
    public void CITYTest() {
        // TODO: test CITY
    }

    /**
     * Test the property 'COUNTRY_CODE'
     */
    @Test
    public void COUNTRY_CODETest() {
        // TODO: test COUNTRY_CODE
    }

    /**
     * Test the property 'DATE_OF_BIRTH'
     */
    @Test
    public void DATE_OF_BIRTHTest() {
        // TODO: test DATE_OF_BIRTH
    }

    /**
     * Test the property 'EMAIL'
     */
    @Test
    public void EMAILTest() {
        // TODO: test EMAIL
    }

    /**
     * Test the property 'FIRST_NAME'
     */
    @Test
    public void FIRST_NAMETest() {
        // TODO: test FIRST_NAME
    }

    /**
     * Test the property 'GENDER'
     */
    @Test
    public void GENDERTest() {
        // TODO: test GENDER
    }

    /**
     * Test the property 'JOB'
     */
    @Test
    public void JOBTest() {
        // TODO: test JOB
    }

    /**
     * Test the property 'LAST_CHANGE'
     */
    @Test
    public void LAST_CHANGETest() {
        // TODO: test LAST_CHANGE
    }

    /**
     * Test the property 'LAST_NAME'
     */
    @Test
    public void LAST_NAMETest() {
        // TODO: test LAST_NAME
    }

    /**
     * Test the property 'MARITAL_STATUS'
     */
    @Test
    public void MARITAL_STATUSTest() {
        // TODO: test MARITAL_STATUS
    }

    /**
     * Test the property 'NATIONALITY'
     */
    @Test
    public void NATIONALITYTest() {
        // TODO: test NATIONALITY
    }

    /**
     * Test the property 'NUMBER_CHILDREN'
     */
    @Test
    public void NUMBER_CHILDRENTest() {
        // TODO: test NUMBER_CHILDREN
    }

    /**
     * Test the property 'PHONE'
     */
    @Test
    public void PHONETest() {
        // TODO: test PHONE
    }

    /**
     * Test the property 'STREET'
     */
    @Test
    public void STREETTest() {
        // TODO: test STREET
    }

    /**
     * Test the property 'ZIP'
     */
    @Test
    public void ZIPTest() {
        // TODO: test ZIP
    }

}
